### ISSUE TITLE
localization?

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/flying-squid#460] opened 2020-11-02 23:45 UTC
Is it possible to do server localization (commands and messages) as in [this module](https://www.npmjs.com/package/msg-localize)?

**Comment by rom1504** [comment] 2020-11-02 23:47
You can check the open PR from @redcarti about that

**Comment by lastuniverse** [comment] 2020-11-02 23:53
Sorry. Lost in the interface)) How can I see the open PR from @redcarti?

**Comment by rom1504** [comment] 2020-11-03 00:03
https://github.com/PrismarineJS/flying-squid/pull/455

**Comment by lastuniverse** [comment] 2020-11-03 00:17
Thanks. I still didn't understand anything) Apparently it's time for me to seriously study the English language and the possibilities of github. Sorry again to distract you.

**Comment by lastuniverse** [comment] 2020-11-03 11:58
Unfortunately, at the moment I do not have time to thoroughly understand your code. Therefore, I cannot create a branch, make changes to it, and offer to merge. But what I saw allows me [to offer this option](https://github.com/PrismarineJS/flying-squid/issues/413#issuecomment-721055157)

**Comment by rom1504** [comment] 2021-01-02 23:57
duplicate of https://github.com/PrismarineJS/flying-squid/issues/413

**Closed by rom1504** 2021-01-02 23:57 UTC
