### ISSUE TITLE
Is this server compatible with 1.11?

### ISSUE THREAD

**Issue by Christian7573** [PrismarineJS/flying-squid#292] opened 2017-02-13 14:27 UTC
Just want to know because I would really like to use this in my projects.

**Comment by rom1504** [comment] 2017-02-13 14:27
not yet. Almost everything is ready but I need to finish https://github.com/PrismarineJS/flying-squid/pull/286 before it actually supports 1.11

**Comment by Christian7573** [comment] 2017-02-13 14:28
Ok!

**Comment by Christian7573** [comment] 2017-02-13 15:55
What version does this currently support?

**Comment by rom1504** [comment] 2017-02-13 16:03
1.8

**Comment by Christian7573** [comment] 2017-02-14 23:41
![image](https://cloud.githubusercontent.com/assets/11007603/22954554/bc5a6620-f2dc-11e6-9db3-38787aeb56c8.png)
I'm getting this error message when running the app. Did a file not download correctly when I downloaded flying squid?

**Comment by Christian7573** [comment] 2017-02-15 00:56
![image](https://cloud.githubusercontent.com/assets/11007603/22956356/2f931cb8-f2e7-11e6-8dcd-94217721e814.png)
Never mind reinstalled flying squid, then got this error

**Comment by mhsjlw** [comment] 2017-02-15 01:02
Have you run `gulp`?

**Comment by Christian7573** [comment] 2017-02-15 01:36
No. I have no clue what gulp is.

**Comment by Creeplays** [comment] 2017-02-15 05:33
Just install new version of node

**Comment by Christian7573** [comment] 2017-02-15 14:21
Thanks! Problem fixed! And should I start developing the server now, or will there be a bunch of changes that I'll need to make when it becomes 1.11 compatible

**Comment by rom1504** [comment] 2017-02-15 14:22
@Christian7573 no you can start developing now, 1.11 compatibility won't change the api too much

**Comment by Christian7573** [comment] 2017-02-17 19:53
Ok, so I got the server up. It seems entities have no AI, food doesn't work, there's no fall damage, rails don't place correctly, and a few other things. Any clue why this is happening? Is some internal plugin failing?
Also, I tried installing flying-squid-essentials. I get an error message saying it can't find the plugin, and I've checked several times to make sure it's in the right folder.

**Comment by rom1504** [comment] 2017-02-18 15:20
> It seems entities have no AI, food doesn't work, there's no fall damage, rails don't place correctly, and a few other things

Yes flying-squid is very far from being feature complete.

**Comment by Christian7573** [comment] 2017-02-18 18:57
Ok

**Comment by javacoolme** [comment] 2017-08-01 05:38
Duplicate of #282?

**Comment by mhsjlw** [comment] 2017-11-18 18:13
Closed as duplicate of #282 which is in turn duplicate of #219

**Closed by mhsjlw** 2017-11-18 18:13 UTC
