### ISSUE TITLE
Server crashed when playing in creative mode

### ISSUE THREAD

**Issue by jessiepathfinder** [PrismarineJS/flying-squid#566] opened 2022-02-17 06:20 UTC
I tried this config here
https://github.com/PrismarineJS/flying-squid#using-as-a-lib
and flying squid crashed shortly after joining. didn't happen in survival.

**Comment by darksunlight** [comment] 2022-02-17 06:23
Can you share the error?

**Comment by jessielesbian** [comment] 2022-02-17 06:36
```
Biomes: { value: chunk.biomes, type: 'intArray' },
                                     ^

TypeError: Cannot read properties of undefined (reading 'biomes')
    at prismarineChunkToNbt (C:\Users\jessi\Desktop\MineIGTT\node_modules\prismarine-provider-anvil\src\1.14\chunk.js:25:38)
    at Anvil.save (C:\Users\jessi\Desktop\MineIGTT\node_modules\prismarine-provider-anvil\src\anvil.js:44:19)
    at World.saveNow (C:\Users\jessi\Desktop\MineIGTT\node_modules\prismarine-world\src\world.js:139:30)
    at Timeout._onTimeout (C:\Users\jessi\Desktop\MineIGTT\node_modules\prismarine-world\src\world.js:147:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

I appreciate this project, and saw that it's undervalued, but it have too many bugs. This error occurred after I've been flying in creative for a while.

**Comment by z46-dev** [comment] 2022-03-05 23:47
This also happens for me too I haven't gotten into too much detail playing, but I went into creative and flew around.
It seemed like it was attempting to load a new chunk

**Comment by darksunlight** [comment] 2022-03-10 00:52
Sometimes I can fly around for over 2 minutes before this happens, but sometimes when my machine is under heavy load it can happen after a few seconds.

**Comment by kf106** [comment] 2022-05-19 20:58
I'm seeing this error regularly too.

**Comment by kf106** [comment] 2022-05-19 21:36
Further investigation: this is highly reproducible by teleporting to a new area where no chunks have been loaded into .mca before.

Function prismarineChunkToNbt is receiving an argument, chunk, that is undefined and hence has no keys. I'm guessing that this is due to the generator function not producing the chunks fast enough and some kind of async problem.

**Comment by Pandapip1** [comment] 2024-01-08 23:31
@rom1504 pretty sure this is now fixed upstream

**Closed** 2024-01-08 23:31 UTC
