### ISSUE TITLE
1.16.1 Destroying block in survival crashes the server

### ISSUE THREAD

**Issue by tumenor** [PrismarineJS/flying-squid#436] opened 2020-08-09 02:01 UTC
TypeError: Cannot read property 'name' of undefined
    at MCServer.serv.spawnObject (src\lib\plugins\spawn.js:39:37)

minecraft-data dependency seem to not have the objects for this version

**Comment by danielpmc** [comment] 2020-10-10 23:52
Any idea if this is going to be fixed soon? im having the same issue lmao

**Comment by bitknox** [comment] 2020-11-02 22:58
This is caused by minecraft-data incorrectly labeling every entity as a mob from 1.11 and up.  See https://github.com/PrismarineJS/minecraft-data/issues/341

**Comment by Creeper09** [comment] 2020-11-11 16:17
so how do we fix it?
or do we just need to wait for flying squid to be updated?

**Comment by rom1504** [comment] 2021-01-02 23:56
fixed now

**Closed by rom1504** 2021-01-02 23:56 UTC
