### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by SecretsMan** [PrismarineJS/flying-squid#336] opened 2018-05-21 12:35 UTC
C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:28
      setTimeout(() => { throw err }, 0)
                         ^

TypeError: require(...).portal_detector is not a function
    at Object.module.exports.player (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\portal.js:5:83)
    at Object.keys.filter.forEach.pluginName (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:22:52)
    at Array.forEach (<anonymous>)
    at Server.serv._server.on (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:22:10)
    at Server.emit (events.js:182:13)
    at loginClient (C:\Users\Rayan Desfossez\Desktop\serv\node_modules\minecraft-protocol\src\server\login.js:125:12)
    at C:\Users\Rayan Desfossez\Desktop\serv\node_modules\minecraft-protocol\src\server\login.js:86:9
    at C:\Users\Rayan Desfossez\Desktop\serv\node_modules\yggdrasil\lib\Server.js:51:7
    at IncomingMessage.<anonymous> (C:\Users\Rayan Desfossez\Desktop\serv\node_modules\phin\lib\phin.compiled.js:1:2111)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I get with error on vanilla setup of flying-squid... on login

**Comment by mhsjlw** [comment] 2018-05-21 12:39
Duplicate of #332

**Closed by mhsjlw** 2018-05-21 12:39 UTC
